services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./django_otp_auth:/app/django_otp_auth
      - ./tests:/app/tests
    environment:
      - DJANGO_SETTINGS_MODULE=tests.settings
      - PYTHONPATH=.
